# -*- coding: utf-8 -*-
"""Chapter_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/nceder/qpb4e/blob/main/code/Chapter%2003/Chapter_03.ipynb

# 3 The Quick Python overview

This notebook contains all of the code examples shown in chapter 3 of The Quick Python Book. You can experiment with these - feel free to change values and see what happens.

For full explanations of the these code snippets, please refer to chapter 3 of The Quick Python Book.

# IMPORTANT!

Run the cell below to load the data files needed for some of the code in this chapter.
"""

!wget https://raw.githubusercontent.com/nceder/qpb4e/main/code/Chapter%2003/shape.py  &> null  && echo Downloaded
!wget https://raw.githubusercontent.com/nceder/qpb4e/main/code/Chapter%2003/wo.py &> null  && echo Downloaded

!touch empty_file
! echo "This is myfile1.txt" > myfile1.txt
! echo "This is myfile2.txt" > myfile2.txt

"""# 3.2 Built-in data types
##3.2.1 Numbers


Python’s four number types are integers, floats, complex numbers, and Booleans:
* Integers—1, –3, 42, 355, 888888888888888, –7777777777 (integers aren’t limited in size except by available memory)
* Floats—3.0, 31e12, –6e-4
* Complex numbers—3 + 2j, –4- 2j, 4.2 + 6.3j
* Booleans—True, False

You can manipulate them by using the arithmetic operators: + (addition), – (subtraction), * (multiplication), / (division), ** (exponentiation), and % (modulus).

The following examples use integers:
"""

x = 5 + 2 - 3 * 2
x

5 / 2

5 // 2

5 % 2

2 ** 8

1000000001 ** 3

"""These examples work with floats, which are based on the doubles in C:"""

x = 4.3 ** 2.4
x

3.5e30 * 2.77e45

1000000001.0 ** 3

"""These examples use complex numbers:"""

(3+2j) ** (2+3j)

x = (3+2j) * (4+9j)
x

x.real

x.imag

"""Several built-in functions can operate on numbers. There are also the library module `cmath` (which contains functions for complex numbers) and the library module `math` (which contains functions for the other three types):"""

round(3.49)

import math
math.ceil(3.49)

"""The following examples use Booleans:

"""

x = False
x

not x

y = True * 2
y

"""## 3.2.2 Lists

Python has a powerful built-in list type:
"""

[]
[1]
[1, 2, 3, 4, 5, 6, 7, 8, 12]
[1, "two", 3, 4.0, ["a", "b"], (5,6)]

"""A list can be indexed from its front or back. You can also refer to a subsegment, or slice, of a list by using slice notation:"""

x = ["first", "second", "third", "fourth"]
x[0]

x[2]

x[-1]

x[-2]

x[1:-1]

x[0:3]

x[-2:-1]

x[:3]

x[-2:]

x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x[1] = "two"
x[8:9] = []
x

x[5:7] = [6.0, 6.5, 7.0]
x

x[5:]

"""Some built-in functions (len, max, and min), some operators (in, +, and *), the del statement, and the list methods (append, count, extend, index, insert, pop, remove, reverse, and sort) operate on lists:"""

x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
len(x)

[-1, 0] + x

x.reverse()
x

"""## 3.2.3 Tuples"""

()
(1,)
(1, 2, 3, 4, 5, 6, 7, 8, 12)
(1, "two", 3, 4.0, ["a", "b"], (5, 6))

"""A list can be converted to a tuple by using the built-in function tuple:

"""

x = [1, 2, 3, 4]
tuple(x)

"""Conversely, a tuple can be converted to a list by using the built-in function list:"""

x = (1, 2, 3, 4)
list(x)

"""## 3.2.4 Strings

String processing is one of Python’s strengths. There are many options for delimiting strings:
"""

"A string in double quotes can contain 'single quote' characters."
'A string in single quotes can contain "double quote" characters.'
'''\tA string which starts with a tab; ends with a newline character.\n'''
"""This is a triple double quoted string - triple quoted strings (single
   or double quoted) are only kind that can contain real newlines."""

"""Strings have several methods to work with their contents..."""

x = "live and     let \t   \tlive"
x.split()

x.replace("    let \t   \tlive", "enjoy life")

""" The `re` library module also contains functions for working with strings:"""

import re
regexpr = re.compile(r"[\t ]+")
regexpr.sub(" ", x)

"""The print function outputs strings. Other Python data types can be easily converted to strings and formatted:"""

e = 2.718
x = [1, "two", 3, 4.0, ["a", "b"], (5, 6)]
print("The constant e is:", e, "and the list x is:", x)

"""Objects are automatically converted to string representations for printing #1.

Placing an `f` in front of a string  #2 inserts the values of variables or expressions in `{}` into the string.
"""

print(f"the value of e is: {e}")                 #2

"""## 3.2.5 Dictionaries

Keys must be of an immutable type #1, including numbers, strings, and tuples. Values can be any kind of object, including mutable types such as lists and dictionaries.
"""

x = {1: "one", 2: "two"}
x["first"] = "one"         #A
x[("Delorme", "Ryan", 1995)] = (1, 2, 3)   #1
list(x.keys())

"""If you try to access the value of a key that isn’t in the dictionary, a `KeyError` exception is raised. To avoid this error, the dictionary method `get` #2 optionally returns a user-definable value when a key isn’t in a dictionary."""

x.get(1, "not available")

x.get(4, "not available")      #2

"""## 3.2.6 Sets, frozensets

 A set in Python is an unordered collection of objects, used in situations where membership and uniqueness in the set are important. Frozensets are similar to sets, but once created are immutable.
"""

x = set([1, 2, 3, 1, 3, 5])
x

1 in x

4 in x

"""## 3.2.7 File objects

A file is accessed through a Python file object:
"""

f = open("myfile", "w")
f.write("First line with necessary newline character\n")
f.write("Second line to write to the file\n")
f.close()
f = open("myfile", "r")
line1 = f.readline()
line2 = f.readline()
f.close()
print(line1, line2)

import os                               #3
directory = os.getcwd()
print(directory)

filename = os.path.join(directory, "myfile")                                          #5
print(filename)
f = open(filename, "r")
print(f.readline())
f.close()

"""# 3.4 Control flow structures
## 3.4.2 if-elif-else statement

The block of code after the first `True` condition (of an `if` or an `elif`) is executed. If none of the conditions is `True`, the block of code after the `else` is executed:
"""

x = 5
if x < 5:
    y = -1
    z = 5
elif x > 5:
    y = 1
    z = 11
else:
    y = 0
    z = 10
print(x, y, z)

"""## 3.4.3 Structural pattern matching

Versions of Python from 3.10 have the match statement with allows for flexible and powerful pattern matching,
"""

# point is an (x, y) tuple
point = (1, 2)

match point:
    case (0, 0):
        print("Origin")
    case (0, y):
        print(f"Y={y}")
    case (x, 0):
        print(f"X={x}")
    case (x, y):
        print(f"X={x}, Y={y}")
    case _:
        raise ValueError("Not a point")

"""
## 3.4.4 The while loop

The `while` loop is executed as long as the condition (which here is `x > y`) is `True`:
"""

u, v, x, y = 0, 0, 100, 30    #A
while x > y:           #B
    u = u + y          #B
    x = x - y          #B
    if x < y + 2:      #B
        v = v + x      #B
        x = 0          #B
    else:              #B
        v = v + y + 2  #B
        x = x - y - 2  #B
    print(f"{u=} {v=}")  #C
print(u, v)

"""## 3.4.5 The for loop

The for loop is simple but powerful because it’s possible to iterate over any iterable type, such as a list or tuple. U
"""

item_list = [3, "string1", 23, 14.0, "string2", 49, 64, 70]
for x in item_list:
    if not isinstance(x, int):
        continue
    if not x % 7:
        print("found an integer divisible by seven: %d" % x)
        break

"""## 3.4.6 Function definition

Python provides flexible mechanisms for passing arguments to functions:
"""

def funct1(x, y, z):
    value = x + 2*y + z**2
    if value > 0:
        return x + 2*y + z**2
    else:
        return 0

u, v = 3, 4
funct1(u, v, 2)

"""Function arguments can be entered either by position or by name (keyword). Here, z and y are entered by name #3"""

funct1(u, z=v, y=2)

""" Function parameters can be defined with defaults that are used if a function call leaves them out #4."""

def funct2(x, y=1, z=1):
    return x + 2 * y + z ** 2

funct2(3, z=4)

"""A special parameter can be defined that collects all extra positional arguments in a function call into a tuple #5."""

def funct3(x, y=1, z=1, *tup):
    print((x, y, z) + tup)

funct3(2)

funct3(1, 2, 3, 4, 5, 6, 7, 8, 9)

"""Likewise, a special parameter can be defined that collects all extra keyword arguments in a function call into a dictionary #6."""

def funct4(x, y=1, z=1, **kwargs):
    print(x, y, z, kwargs)
funct4(1, 2, m=5, n=9, z=3)

"""## 3.4.7 Exceptions

Exceptions (errors) can be caught and handled by using the `try-except-else-finally` compound statement. This statement can also catch and handle exceptions you define and raise yourself.
"""

class EmptyFileError(Exception):     #A
    pass
file_names = ["myfile1.txt", "non_existent", "empty_file", "myfile2.txt"]
for file_name in file_names:
    try:                             #B
        file = open(file_name, 'r')
        line = file.readline()          #C
        if line == "":
            file.close()
            raise EmptyFileError("{file_name}: is empty")      #D
    except IOError as error:
        print(f"{file_name}: could not be opened: {error.strerror}")
    except EmptyFileError as error:
        print(error)
    else:                             #E
        print(f"{file_name}: {line}")
    finally:
        print("Done processing", file_name)                       #F

"""## 3.4.8 Context handling using the `with` keyword

A more streamlined way of encapsulating the try-except-finally pattern is to use the with keyword and a context manager. This example shows opening and reading a file by using `with` and a context manager.
"""

filename = "myfile1.txt"
with open(filename, "r") as file:
    for line in file:
        print(line)

"""That code is equivalent to this code:"""

filename = "myfile1.txt"
try:
    file = open(filename, "r")
    for line in file:
        print(line)
except Exception as e:
    raise e
finally:
    file.close()

"""# 3.5 Module creation

It’s easy to create your own modules, which can be imported and used in the same way as Python’s built-in library modules. The example in this listing is a deliberately oversimplified module with one function that prompts the user to enter a filename and determines the number of times that words occur in this file.
"""

"""wo module. Contains function: words_occur()"""
# interface functions
def words_occur():
    """words_occur() - count the occurrences of words in a file."""
    # Prompt user for the name of the file to use.
    file_name = input("Enter the name of the file: ")
    # Open the file, read it and store its words in a list.
    file = open(file_name, 'r')
    word_list = file.read().split()
    file.close()
    # Count the number of occurrences of each word in the file.
    occurs_dict = {}
    for word in word_list:
        # increment the occurrences count for this word
        occurs_dict[word] = occurs_dict.get(word, 0) + 1
    # Print out the results.
    print(f"File {file_name} has {len(word_list)} words ({len(occurs_dict)} are unique)")
    print(occurs_dict)
if __name__ == '__main__':
    words_occur()

"""If a file is in the current directory or in one of the directories on the module search path, which can be found in sys.path, it can be imported like any of the built-in library modules by using the import statement:

"""

import wo
wo.words_occur()

"""Note that if you change the file wo.py on disk, import won’t bring your changes into the same interactive session. You use the reload function from the imp library in this situation:

"""

import imp
imp.reload(wo)

"""#3.4 Object oriented programming

Python provides full support for OOP. Listing 3.4 is an example that might be the start of a simple shapes module for a drawing program.

### Listing 3.4 File shape.py
"""

# Commented out IPython magic to ensure Python compatibility.
"""shape module. Contains classes Shape, Square and Circle"""
class Shape:
    """Shape class: has method move"""
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def move(self, deltaX, deltaY):
        self.x = self.x + deltaX
        self.y = self.y + deltaY
class Square(Shape):
    """Square Class:inherits from Shape"""
    def __init__(self, side=1, x=0, y=0):
        Shape.__init__(self, x, y)
        self.side = side
class Circle(Shape):
    """Circle Class: inherits from Shape and has method area"""
    pi = 3.14159
    def __init__(self, r=1, x=0, y=0):
        Shape.__init__(self, x, y)
        self.radius = r
    def area(self):
        """Circle area method: returns the area of the circle."""
        return self.radius * self.radius * self.pi
    def __str__(self):
        return "Circle of radius %s at coordinates (%d, %d)"\
#                % (self.radius, self.x, self.y)

import shape
c1 = shape.Circle()
c2 = shape.Circle(5, 15, 20)
print(c1)

print(c2)

c2.area()

c2.move(5,6)
print(c2)

