# -*- coding: utf-8 -*-
"""Chapter_07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/nceder/qpb4e/blob/main/code/Chapter%2007/Chapter_07.ipynb

# 7 Dictionaries

# 7.1 What is a dictionary?
"""

x = []
y = {}

y[0] = 'Hello'
y[1] = 'Goodbye'

x[0] = 'Hello'

print(y[0])
print(y[1] + ", Friend.")

y['greeting'] = "Bon jour"
y['farewell'] = "Adios"
print(y['greeting'])
print(y['farewell'] + ", Friend.")

english_to_french = {}                     #A
english_to_french['red'] = 'rouge'         #B
english_to_french['blue'] = 'bleu'
english_to_french['green'] = 'vert'
print("red is", english_to_french['red'])  #C

"""### Try This: Create a dictionary
Write the code to ask the user for three names and three ages. After the names and ages are entered, ask the user for one of the names, and print the correct age.

"""



name_age = {}
for i in range(3):
    name = input("Name? ")
    age = int(input("Age? "))
    name_age[name] = age

name_choice = input("Name to find? ")
print(name_age[name_choice])

"""# 7.2 Other dictionary operations"""

english_to_french = {'red': 'rouge', 'blue': 'bleu', 'green': 'vert'}

len(english_to_french)

list(english_to_french.keys())

list(english_to_french.values())

list(english_to_french.items())

list(english_to_french.items())

del english_to_french['green']
list(english_to_french.items())

'red' in english_to_french

'orange' in english_to_french

print(english_to_french.get('blue', 'No translation'))

print(english_to_french.get('chartreuse', 'No translation'))

print(english_to_french.setdefault('chartreuse', 'No translation'))

x = {0: 'zero', 1: 'one'}
y = x.copy()
y

z = {1: 'One', 2: 'Two'}
x = {0: 'zero', 1: 'one'}
x.update(z)
x

"""### Quick Check: Dictionary operations
Assume that you have a dictionary `x = {'a':1, 'b':2, 'c':3, 'd':4}` and a dictionary `y = {'a':6, 'e':5, 'f':6}`. What would be the contents of x after the following snippets of code have executed?:
```
del x['d']
z = x.setdefault('g', 7)
x.update(y)
```
"""



# @title
x = {'a':1, 'b':2, 'c':3, 'd':4}
y = {'a':6, 'e':5, 'f':6}

del x['d']
print(x)

# @title
z = x.setdefault('g', 7)
print(x)

# @title
x.update(y)
print(x)

"""# 7.3 Word Counting"""

sample_string = "To be or not to be"
occurrences = {}
for word in sample_string.split():
    occurrences[word] = occurrences.get(word, 0) + 1    #A

for word in occurrences:
    print("The word", word, "occurs", occurrences[word],
           "times in the string")

"""# 7.4 What can be used as a key?

### Quick Check: What can be a key?
Decide which of the following expressions can be a dictionary key:

`1; 'bob'; ('tom', [1, 2, 3]); ["filename"]; "filename"; ("filename",  "extension") `

# 7.5 Sparse matrices
"""

matrix = [[3, 0, -2, 11], [0, 9, 0, 0], [0, 7, 0, 0], [0, 0, 0, -5]]
rownum = 0
colnum = 1
element = matrix[rownum][colnum]

matrix = {(0, 0): 3, (0, 2): -2, (0, 3): 11,
          (1, 1): 9, (2, 1): 7, (3, 3): -5}
if (rownum, colnum) in matrix:
    element = matrix[(rownum, colnum)]
else:
    element = 0
element = matrix.get((rownum, colnum), 0)

matrix = {(0, 0): 3, (0, 2): -2, (0, 3): 11,
          (1, 1): 9, (2, 1): 7, (3, 3): -5}
if (rownum, colnum) in matrix:
    element = matrix[(rownum, colnum)]
else:
    element = 0
element = matrix.get((rownum, colnum), 0)

"""# 7.6 Dictionaries as caches

### Try This: Using dictionaries
Suppose that you're writing a program that works like a spreadsheet. How might you use a dictionary to store the contents of a sheet? Write some sample code to both store a value and retrieve a value in a particular cell. What might be some drawbacks to this approach?

You could use tuples of row, column values as keys to store the values in a dictionary. One drawback would be that the keys wouldn’t be sorted, so you’d have to manage that situation as you grabbed the keys/values to render as a spreadsheet.
"""



sheet = {}
sheet[('A', 1)] = 100
sheet[('B', 1)] = 1000

print(sheet[('A', 1)])

"""# 7.8 Lab 7: Word counting

In the previous lab, you took the text of the first chapter of Moby Dick, normalized the case, removed punctuation, and wrote the separated words to a file. In this lab, we will use the file created in chapter 6 to count the number of times each word occurs.

To do this we will read the file, and use a dictionary as described above to count the occurrences, using the words as the keys and the number of occurrences as the values. Once we have processed the file, we’ll print out the five most common and five least common words and the number of times they occur.
To open and read the file we can use code that’s similar to what we used the last time, but we won’t need an output file:
```with open("moby_01_clean.txt", "r") as infile:
    for word in infile:
        # use stip() method to remove any extra whitespace
        # increase the count for current word
```
In addition to using a dictionary to count occurrences, you'll need to use the `items()`1 method to get the keys and values as a series of tuples that you can sort. For this you may need to refer to the chapter on lists.

### Run the cell below to get the file moby_01_clean.txt
"""

!wget https://raw.githubusercontent.com/nceder/qpb4e/main/code/Chapter%2007/moby_01_clean.txt  &> null  && echo Downloaded

# Create your solution in this cell

# Solution created by the author

word_count = {}
with open("moby_01_clean.txt", "r") as infile:
    for word in infile:
        # use strip() method to remove any extra whitespace
        word = word.strip()

        # increase the count for current word
        count = word_count.setdefault(word, 0)
        count += 1
        word_count[word] += 1

word_list = list(word_count.items())
word_list.sort(key=lambda x: x[1])
print("Most common words:")
for word in reversed(word_list[-5:]):
    print(word)
print("\nLeast common words:")
for word in word_list[:5]:
    print(word)

# Generated by Colaboratory

# prompt: Open the file moby_01_clean.txt and use a dictionary to count the
#         occurrences of each word. Do not use a Counter. Print the five
#         most common words and their number of occurrences. Print the
#         five least common words and their number of occurrences.

# Open the file and read the text into a variable.
with open('moby_01_clean.txt', 'r') as f:
  text = f.read()

# Split the text into words.
words = text.split()

# Create a dictionary to count the occurrences of each word.
word_counts = {}
for word in words:
  if word not in word_counts:
    word_counts[word] = 0
  word_counts[word] += 1

# Find the five most common words and their number of occurrences.
most_common = sorted(word_counts.items(), key=lambda item: item[1], reverse=True)[:5]

# Find the five least common words and their number of occurrences.
least_common = sorted(word_counts.items(), key=lambda item: item[1])[:5]

# Print the results.
print("Most common words:")
for word, count in most_common:
  print(f"{word}: {count}")

print("\nLeast common words:")
for word, count in least_common:
  print(f"{word}: {count}")

# Generated by Copilot

# Open the file
with open('moby_01_clean.txt', 'r') as file:
    # Read the file content
    content = file.read()

# Split the content into words
words = content.split()

# Count the occurrences of each word using a dictionary
word_counts = {}
for word in words:
    if word in word_counts:
        word_counts[word] += 1
    else:
        word_counts[word] = 1

# Sort the word counts in descending order
sorted_word_counts = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)

# Print the five most common words and their occurrences
print("Five most common words:")
for word, count in sorted_word_counts[:5]:
    print(f"{word}: {count}")

# Print the five least common words and their occurrences
print("Five least common words:")
for word, count in sorted_word_counts[-5:]:
    print(f"{word}: {count}")