# -*- coding: utf-8 -*-
"""Chapter_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/nceder/qpb4e/blob/main/code/Chapter%2002/Chapter_02.ipynb

# 2.2 Getting started with Python and Colaboratory

# 2.3 Hello world
"""

# After running the first time, experiment with printing different strings (in quotes)
print("Hello, World!")

# this cell will raise a syntax error
print("Hello, World!"

"""# 2.4 Using `help` and `dir` to explore Python"""

help()

x = 2
help(x)

dir()

dir(int)

help()

